### ISSUE TITLE
d3-node is giving error in NPM run build i.e for production environment

### ISSUE THREAD

**Issue by atulsingh0913** [d3-node/choropleth-us-counties#1]
d3-node is not working with npm run build , in create react app , with production environment build.
It gives the following message

```
Failed to compile.
Failed to minify the code from this file: 
 	./node_modules/d3-node/node_modules/jsdom/lib/jsdom/living/generated/utils.js:5 
```

**Comment by bradoyler** [comment]
If you're using React & D3 you should go this route: https://medium.com/@zimrick/how-to-create-pure-react-svg-maps-with-topojson-and-d3-geo-e4a6b6848a98

React has its own isomorphic Dom rendering path. So you have to do it the "React way".
